In [13]:
using LinearAlgebra

## 1 Matrices

### 1.1 Introduction

In [14]:
people = [1.70 70 23; 1.75 60 45; 1.60 52 25; 1.81 72 30]

4×3 Array{Float64,2}:
 1.7   70.0  23.0
 1.75  60.0  45.0
 1.6   52.0  25.0
 1.81  72.0  30.0

In [15]:
A = [1 0 -4; 4 -3 2]

2×3 Array{Int64,2}:
 1   0  -4
 4  -3   2

In [16]:
A[1,1], A[1,2], A[1,3], A[2,1], A[2,2], A[2,3] # a11

(1, 0, -4, 4, -3, 2)

In [17]:
A = [3^2 1 log(1); 2 2^2 5]

2×3 Array{Float64,2}:
 9.0  1.0  0.0
 2.0  4.0  5.0

In [18]:
B = [9 sin(π/2) 0; 2 4 5]

2×3 Array{Float64,2}:
 9.0  1.0  0.0
 2.0  4.0  5.0

In [19]:
A == B

true

### 1.2 ESPECIALS SORT OF MATRICES

#### 1.2.1 Square Matrix $ (m=n) $

In [20]:
[1 -2 0; 3 0 1; 4 5 6]

3×3 Array{Int64,2}:
 1  -2  0
 3   0  1
 4   5  6

In [21]:
[8]

1-element Array{Int64,1}:
 8

#### 1.2.2 Zero Matrix $ (a_{ij} = 0, \quad \forall i,j) $

In [22]:
zeros(2,2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [23]:
zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

#### 1.2.3 Column Matrix $ (n = 1) $

In [24]:
[1, 4, 3]

3-element Array{Int64,1}:
 1
 4
 3

In [99]:
rand(3,1)

3×1 Array{Float64,2}:
 0.33568176965981666
 0.7784441253141268
 0.42362287949612476

#### 1.2.4 Row Matrix $( m = 1) $

In [55]:
[3 0 -1]

1×3 Array{Int64,2}:
 3  0  -1

In [98]:
rand(1,3)

1×3 Array{Float64,2}:
 0.0968963  0.357746  0.370005

#### 1.2.5 Diagonal Matrix

#### 1.2.6 Identity Matrix

In [121]:
I(3)

3×3 Diagonal{Bool,Array{Bool,1}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [86]:
UniformScaling(1)

UniformScaling{Int64}
1*I

In [92]:
1.0 * Matrix(I,3,3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [100]:
[2 -1 0; 0 -1 4; 0 0 3]

3×3 Array{Int64,2}:
 2  -1  0
 0  -1  4
 0   0  3

#### 1.2.9 Symetric Matrix $ (m = n \quad and \quad a_{ij} = a_{ji}) $
- $A = A^t$

In [123]:
A = [4 3 -1; 3 2 0; -1 0 5]

3×3 Array{Int64,2}:
  4  3  -1
  3  2   0
 -1  0   5

In [124]:
A' #transpose

3×3 Adjoint{Int64,Array{Int64,2}}:
  4  3  -1
  3  2   0
 -1  0   5

In [126]:
A = Symmetric(rand(3,3))

3×3 Symmetric{Float64,Array{Float64,2}}:
 0.525552  0.588796  0.880869
 0.588796  0.74324   0.184864
 0.880869  0.184864  0.736336

In [127]:
A'

3×3 Symmetric{Float64,Array{Float64,2}}:
 0.525552  0.588796  0.880869
 0.588796  0.74324   0.184864
 0.880869  0.184864  0.736336

In [128]:
A == A'

true

### 1.3 Matrix Operations